# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 00:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('service', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('comments', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[(b'Pick One', b'Pick One'), (b'Under 30', b'Under 30'), (b'30-40', b'30-40'), (b'41-50', b'41-50'), (b'51-60', b'51-60'), (b'61-70', b'61-70'), (b'71+', b'71+')], default='Pick One', max_length=255)),
                ('status', models.CharField(choices=[(b'Pick One', b'Pick One'), (b'Single', b'Single'), (b'Married', b'Married'), (b'Widowed', b'Widowed')], default='Pick One', max_length=255)),
                ('accomplice', models.CharField(choices=[(b'Pick One', b'Pick One'), (b'Single', b'Single'), (b'Groups', b'Groups'), (b'Family', b'Family'), (b'Grandchildren', b'Grandchildren')], default='Pick One', max_length=255)),
                ('interests', models.CharField(choices=[(b'Pick One', b'Pick One'), (b'Ocean Cruising', b'Ocean Cruising'), (b'River Cruising', b'River Cruising'), (b'Sailing', b'Sailing'), (b'Canoeing', b'Canoeing'), (b'Hiking', b'Hiking'), (b'Backpacking', b'Backpacking'), (b'Biking', b'Biking'), (b'Land Travel', b'Land Travel'), (b'Bus Tours', b'Bus Tours')], default='Pick One', max_length=255)),
                ('destinations', models.CharField(choices=[(b'Pick One', b'Pick One'), (b'Europe', b'Europe'), (b'Asia', b'Asia'), (b'Caribbean', b'Caribbean'), (b'Africa', b'Africa'), (b'Australia', b'Australia'), (b'Canada', b'Canada'), (b'US', b'US'), (b'South America', b'South America')], default='Pick One', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
